# Generated by Django 4.2.3 on 2023-07-31 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bill_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bill_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bill_zip',
        ),
    ]
