# Generated by Django 4.2.3 on 2023-07-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_order_bill_city_remove_order_bill_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
