# Generated by Django 4.2.3 on 2023-07-27 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_item_order_remove_photo_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='title',
            new_name='name',
        ),
    ]
