# Generated by Django 4.2.3 on 2023-07-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='theme',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
