# Generated by Django 4.2.3 on 2023-08-02 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='photos',
            field=models.ManyToManyField(blank=True, to='gallery.photo'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
